name: "El planeta de Nano (sin parámetros)"
attire:
  active: El planeta de Nano
  user_permissions:
    can_toggle_visibility: false
  visible: true
blocks:
  defaultToolbox: |
      <category name="Comandos primitivos">
        <block type="MoverANanoALaDerecha"></block>
        <block type="MoverANanoHaciaArriba"></block>
        <block type="VolverANanoAlBordeIzquierdo"></block>
        <block type="ComerBanana"></block>
      </category>
      <category name="Mis procedimientos" custom="PROCEDURE_CALLS">  </category>
      <category name="Repeticiones">
        <block type="RepeticionSimple"></block>
      </category>
      <category name="Valores">
        <block type="math_number"></block>
      </category>
      <category name="Definiciones">
        <block type="procedures_defnoreturnnoparams"></block>
      </category>
board:
  active: 1
  initial_board_source: active
  user_permissions:
    can_change_initial_board: true
    can_change_initial_board_source: true
    can_change_source: false
    can_edit_board: false
    can_view_size_section: false
    can_view_attire_section: false
  visible_edition: false
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
library:
  visible: false
source:
  visible: true
  percentage: 0.75
