name: Cuadrados
rules:
  - image: Fondo.png
    when:
      black: 0
      blue: 0
      green: 0
      red: 0
  - image: Azul.png
    when:
      black: 0
      blue: 1
      green: 0
      red: 0
  - image: Negro.png
    when:
      black: 1
      blue: 0
      green: 0
      red: 0
  - image: Rojo.png
    when:
      black: 0
      blue: 0
      green: 0
      red: 1
  - image: Verde.png
    when:
      black: 0
      blue: 0
      green: 1
      red: 0
  - image: Violeta.png
    when:
      black: 0
      blue: 1
      green: 0
      red: 1
