name: Programando en cuadriculado
attire:
  active: Programando en cuadriculado
  user_permissions:
    can_toggle_visibility: false
  visible: true
blocks:
  defaultToolbox: |
      <category name="Comandos primitivos">
        <block type="Pintar"></block>
        <block type="MoverAlNorte"></block>
        <block type="MoverAlEste"></block>
        <block type="MoverAlSur"></block>
        <block type="MoverAlOeste"></block>
      </category>
      <category name="Mis procedimientos" custom="PROCEDURE_CALLS">  </category>
      <category name="Repeticiones">
        <block type="RepeticionSimple"></block>
      </category>
      <category name="Valores">
        <block type="math_number"></block>
      </category>
      <category name="Definiciones">
        <block type="procedures_defnoreturnnoparams"></block>
      </category>
board:
  active: 1
  initial_board_source: random
  user_permissions:
    can_change_source: false
    can_edit_board: false
    can_view_size_section: false
  visible_edition: false
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
library:
  visible: false
source:
  visible: true
  percentage: 0.75
