name: Laberinto con queso
attire:
  active: Laberinto con queso
  user_permissions:
    can_toggle_visibility: false
  visible: true
blocks:
  defaultToolbox: |
      <category name="Comandos primitivos">
        <block type="AvanzarUnPasoSegúnLaFlecha"></block>
        <block type="ComerElQueso"></block>
      </category>
      <category name="Mis procedimientos" custom="PROCEDURE_CALLS">  </category>
      <category name="Repeticiones">
        <block type="RepeticionCondicional"></block>
      </category>
      <category name="Alternativas">
        <block type="AlternativaSimple"></block>
      </category>
      <category name="Sensores">
        <block type="hayQuesoAcá"></block>
        <block type="estoyEnLaMeta"></block>
      </category>
      <category name="Definiciones">
        <block type="procedures_defnoreturnnoparams"></block>
      </category>
board:
  active: 1
  initial_board_source: random
  user_permissions:
    can_change_source: false
    can_edit_board: false
    can_view_size_section: false
  visible_edition: false
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
library:
  visible: false
source:
  visible: true
  percentage: 0.75
