name: Recuerden la contraseña
attire:
  active: El salón
  user_permissions:
    can_toggle_visibility: false
  visible: true
blocks:
  defaultToolbox: |
      <category name="Comandos primitivos">
        <block type="AbrirElCuaderno"></block>
        <block type="MoverALaDocenteAl_"></block>
        <block type="EscribirLaContraseña_"></block>
        <block type="laContraseñaEscritaEnElCuaderno"></block>
      </category>
      <category name="Mis procedimientos" custom="PROCEDURE_CALLS">  </category>
      <category name="Repeticiones">
        <block type="RepeticionSimple"></block>
        <block type="RepeticionCondicional"></block>
      </category>
      <category name="Alternativas">
        <block type="AlternativaSimple"></block>
      </category>
      <category name="Variables">
        <block type="Asignacion"></block>
      </category>
      <category name="Valores">
        <block type="math_number"></block>
        <block type="DireccionSelector"></block>
      </category>
      <category name="Sensores">
        <block type="hayQuesoAcá"></block>
        <block type="estoyEnLaMeta"></block>
      </category>
      <category name="Mis funciones" custom="FUNCTION_CALLS">        </category>
      <category name="Definiciones">
        <block type="procedures_defreturnsimplewithparams"></block>
        <block type="procedures_defnoreturn"></block>
      </category>
board:
  active: 1
  initial_board_source: random
  user_permissions:
    can_change_source: false
    can_edit_board: false
  visible_edition: false
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
library:
  visible: false