name: La cena de Dino
attire:
  active: La cena de Dino
  user_permissions:
    can_toggle_visibility: false
  visible: true
blocks:
  defaultToolbox: | 
      <category name="Comandos primitivos">
        <block type="MoverADinoAl_"></block>
        <block type="CambiarADinoDeFila"></block>
        <block type="Comer_"></block>
      </category>
      <category name="Mis procedimientos" custom="PROCEDURE_CALLS">  </category>
      <category name="Repeticiones">
        <block type="RepeticionSimple"></block>
        <block type="RepeticionCondicional"></block>
      </category>
      <category name="Alternativas">
        <block type="AlternativaSimple"></block>
        <block type="AlternativaCompleta"></block>
      </category>
      <category name="Valores">
        <block type="math_number"></block>
        <block type="DireccionSelector"></block>
      </category>
      <category name="Sensores">
        <block type="estáDinoEnElInicioDeLaFila"></block>
        <block type="hay_"></block>
      </category>
      <category name="Operadores">
        <block type="OperadorLogico"></block>
        <block type="not"></block>
      </category>
      <category name="Definiciones">
        <block type="procedures_defnoreturnnoparams"></block>
      </category>
board:
  active: 1
  initial_board_source: random
  user_permissions:
    can_change_source: false
    can_edit_board: false
  visible_edition: false
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
library:
  visible: false
source:
  visible: true
  percentage: 0.65  
  